version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: lumieresecrete-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME:-lumieresecrete_db}
      POSTGRES_USER: ${DJANGO_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-postgres}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DJANGO_DB_USER:-postgres} -d ${DJANGO_DB_NAME:-lumieresecrete_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumieresecrete-web
    env_file:
      - .env
    environment:
      # Переопределяем хост БД для контейнера
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DEBUG: "False"
      # Укажите фикстуру при необходимости (пример):
      INITIAL_FIXTURE: /srv/app/lumieresecrete/backups/backup-20251114-214816.json
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket,sys; s=socket.socket(); s.settimeout(2); s.connect((\"127.0.0.1\",8000)); s.close()' "]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.11
    container_name: lumieresecrete-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  # Профиль для разработки: автоперезагрузка и монтирование кода
  web-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumieresecrete-web-dev
    env_file:
      - .env
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DEBUG: "True"
      # INITIAL_FIXTURE: /srv/app/lumieresecrete/backups/backup-20251114-214816.json
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket,sys; s=socket.socket(); s.settimeout(2); s.connect((\"127.0.0.1\",8000)); s.close()' "]
    
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./lumieresecrete:/srv/app/lumieresecrete:delegated
